export const changelogs = [
    // Add more from top
    { date: '18/01/2024', description: '• Fixed iOS unable to import images.' },
    { date: '17/01/2024', description: '• Added Kaalaa Baunaa and Shamane banners.\n • Updated 1.3 part 1 Event Shop.' },
    { date: '16/01/2024', description: '• Added Centurion banner.' },
    { date: '15/01/2024', description: '• Added "Level Up" function where you can consume your warehouse materials to update arcanist to goal status. Try it out by left clicking an arcanist.' },
    { date: '14/01/2024', description: '• Home UI improvements.' },
    { date: '13/01/2024', description: '• The algorithm for image preprocessing has been modified, requiring observation for evaluation.' },
    { date: '12/01/2024', description: '• Fixed a bug where pity count in summon history is displayed incorrectly when other rarities are present.' },
    { date: '11/01/2024', description: '• Updated ES translations\n • Added Jiu Niangzi, Енисе́й and updated previous missing data.' },
    { date: '10/01/2024', description: '• Updated KR translations\n • vertin wheel vertin wheel vertin wheel.' },
    { date: '08/01/2024', description: '• Improved Golden Thread OCR.\n • Tracker UI changes.' },
    { date: '07/01/2024', description: '• Added French translations thanks to я герой#3673. \n • Improved Japanese translations thanks to yagochi. \n • Fixed X turning into 37 and crop problems. \n • Added 50/50 win/lose indicator.' },
    { date: '06/01/2024', description: '• Added Spanish translations thanks to mgeshagrath. \n • Added Russian translations thanks to spun4ik and dagufz37. \n • Released 1.3 Arcanists.' },
    { date: '05/01/2024', description: '• Big Summon Tracker Update. \n • Added Japanese translations thanks to yagochi.' },
    { date: '04/01/2024', description: '• Added Korean translations thanks to CaptinRegulus.\n • Added Banner Type for Tracker.' },
    { date: '03/01/2024', description: '• Improved i18n. \n • Improved Tracker OCR' },
    { date: '02/01/2024', description: '• Error log for Summon Tracker.' },
    { date: '29/12/2023', description: '• Added more languages! vi-VN, zh-CN, zh-TW have been fully translated. We need your help!' },
    { date: '28/12/2023', description: '• Summon Tracker out of beta release. \n • Various UI updates.' },
    { date: '26/12/2023', description: '• Improved OCR for 5*. \n • Updated Stage Data and Greedy Method improvements. \n • Added Ezra Theodore and Desert Flanndel.' },
    { date: '25/12/2023', description: '• Improved Activity Settings. UI Improvements.' },
    { date: '24/12/2023', description: '• UI Improvements\n • Wilderness output is now considered for calculations.\n • Merry Christmas.' },
    { date: '23/12/2023', description: '• UI Improvements for goals and crafting list. \n • Added Goal Button.' },
    { date: '21/12/2023', description: '• UI Improvements. \n • Added Goals and Crafting List.' },
    { date: '20/12/2023', description: '• Yet another warehouse update. \n • Summon Tracker. Beta. \n • Added Greedy method to prioritize Purple Materials ' },
    { date: '16/12/2023', description: '• Add names to 1.4 data. UI improvements.\n • Added Activity Settings for Roaring Month and Refills.' },
    { date: '15/12/2023', description: '• Updated storing. Prior selected data will be corrupted, please head to profile to reset.' },
    { date: '14/12/2023', description: '• Warehouse bug fixes (again), changed t6 resonate materials to casket. Sorry for the inconvenience but please reset your warehouse.\n • Added 6, Spathodea and Ulu. Updated arcanists.json\n • Various bug fixes and UI improvements.' },
    { date: '12/12/2023', description: '• Optimized farming route, from the help of Fran!' },
    { date: '05/12/2023', description: '• Added Profile. WIP.' },
    { date: '04/12/2023', description: '• Updated credits, minor bug fixes.' },
    { date: '03/12/2023', description: '• Fixed wrong jsons. Hopefully it is correct now.\n • Soldius. \n • Added 1.2 event shops. Two buttons, all the items.' },
    { date: '02/12/2023', description: '• Fixed warehouse, added Tooth Fairy and Changeling to released.\n • Fixed more warehouse bugs, added reset button.\n • Fixed MORE warehouse bugs.' },
    { date: '01/12/2023', description: '• Warehouse filter is broken, temporary disabled.' },
    { date: '30/11/2023', description: '• Added Warehouse. Fixed wrong Insight levels and unreleased Arcanists' },
    { date: '29/11/2023', description: '• First release.' }
];
