export const changelogs = [
    // Add more from top
    { date: '10/05/2024', description: '• Added Ezra banner, I forgor.' },
    { date: '26/04/2024', description: '• Added Windsong as unreleased character.' },
    { date: '20/04/2024', description: '• Improved French translations by Sillight.' },
    { date: '18/04/2024', description: '• Added Spathodea banner. Added Tooth Fairy + Centurion double banner.' },
    { date: '16/04/2024', description: '• Added Spathodea, Ezra, Ulu and Flannel as released arcanists.' },
    { date: '13/04/2024', description: '• The site\'s URL has been updated from windbow27.github.io/Kornblume/ to windbow27.github.io/kornblume/ (with a lowercase k).' },
    { date: '12/04/2024', description: '• Added Vila and Avgust as unreleased arcanists.' },
    { date: '09/04/2024', description: '• Improved Russian translations by mushel2442.' },
    { date: '04/04/2024', description: '• Fixed syncing bug. \n • For the last time, import error is caused by OCR failing to read images or missing images from user, doing single pulls or order of images DOES NOT matter.' },
    { date: '01/04/2024', description: '• Nothing happened.' },
    { date: '28/03/2024', description: '• Added 6 banner.' },
    { date: '25/03/2024', description: '• Fixed item images sometimes not being loaded (hopefully). \n • UI update for tooltips.' },
    { date: '24/03/2024', description: '• Added Marcus as unreleased arcanist.' },
    { date: '20/03/2024', description: '• Updated Spanish translations by mgeshagrath.\n • Fixed (lazily) "Add Pull" UI bug. \n • Fixed dead link in Tracker Tutorial. \n • Fixed another Editor Tracker bug. Hopefully it works now?' },
    { date: '19/03/2024', description: '• Updated zh Chinese stage names by ryle798.' },
    { date: '16/03/2024', description: '• Added stage names. \n • UI improvements.' },
    { date: '13/03/2024', description: '• Fixed Tracker Editor only saving one type of section. \n • Updated French translations by sillight. \n • Updated zh Chinese translations by ryle798. \n • Fixed missing Spanish translations. \n • Updated Viet translations.' },
    { date: '12/03/2024', description: '• Updated notifications. Again, please read Summon Tracker Tutorial. \n • Google Sync seems stable, should be good to use now.' },
    { date: '10/03/2024', description: '• UI "fixes". \n • Let me know if anything looks funky.' },
    { date: '09/03/2024', description: '• Added Tracker Editor. \n • Updated stats for released arcanists by Heightweight.' },
    { date: '08/03/2024', description: '• Added Google Drive Sync. \n • Added The First Milestone banner.' },
    { date: '05/03/2024', description: '• Planner has been modified and upgraded. Enjoy almost lag free planning experience.' },
    { date: '04/03/2024', description: '• Cleaning up item names in json and bug fixes. \n • Added automatic Greedy mode. \n • Optimized images for faster load time. \n • Updated zh Chinese translations by ryle798.' },
    { date: '02/03/2024', description: '• Fixed 1.4 items not being added to Warehouse. \n • Updated warehouse order to match ingame.  \n • Updated Indonesia translations by ArieKee.' },
    { date: '01/03/2024', description: '• Updated Items and Stages to use 1.4 drop rates. \n • Corrected some item names and descriptions.' },
    { date: '29/02/2024', description: '• Deployed 1.4 update. \n • Added 37 banner.' },
    { date: '27/02/2024', description: '• UI improvements. \n • Removed Greedy (experimental). \n • 1.4 drop data will be enabled on 11 A.M 29/02/2024. \n • Updated Indonesia translations by ArieKee. \n • Updated zh Chinese translations by ryle798.' },
    { date: '25/02/2024', description: '• Added Lilya banner. \n • Added a warning to ignore low opacity materials in planner crafting section.' },
    { date: '24/02/2024', description: '• Added 37 and 6 as released. \n • Added Getian and Isolde as unreleased. \n • Added Quick Goal button (i3 lv30 r10 for 5-6* and i2 lv50 r10 otherwise) \n • There were a lot of updates recently, you guys better go spread the words :gun: \n • And as always, please let me know if there are bugs.' },
    { date: '23/02/2024', description: '• UI improvements. If UI looks funky with your device, please let me know. \n • Updated Korean translations by CaptinRegulus.' },
    { date: '22/02/2024', description: '• UI improvements. \n • Updated French translations by sillight. \n • Updated Spanish translations by mgeshagrath. \n • Updated Indonesia translations by ArieKee. \n • Updated Viet translations.' },
    { date: '21/02/2024', description: '♪ It took me ♪ 10 days ♪ to get this feature to be done ♪ \n ♪ I realized ♪ it broke down ♪ in 2 seconds ♪ \n ♪ THAT\'S ABOUT IT ♪' },
    { date: '20/02/2024', description: '• Added Arcanists page, work in progress.\n • Added Items page. See the information, its droprate and usages here. \n • Added Stages page to look up stages material drops.' },
    { date: '17/02/2024', description: '• Fixed 50/50 Win Rate displayed incorrectly when last pull is a Lose Rate Up.' },
    { date: '13/02/2024', description: '• We have switched to using data provided by shiroinegai. Thank you for your hard work.' },
    { date: '12/02/2024', description: '• Added Indonesia translation by ArieKee.' },
    { date: '11/02/2024', description: '• Added Ms. NewBabel banner, good luck rolling her ;) \n • Happy Lunar new year.' },
    { date: '08/02/2024', description: '• Added 1.3 pt2 shop, Shamane banner. Fixed jukebox rewards.' },
    { date: '02/02/2024', description: '• Added a link to timekeeper.top, also try them.' },
    { date: '30/01/2024', description: '• Added Substitute methods to Tracker' },
    { date: '29/01/2024', description: '• Tracker algorithm was modified. Please let us know if it\'s working via Comments/Bug Reports.' },
    { date: '28/01/2024', description: '• Added Medicine Pocket banner.' },
    { date: '19/01/2024', description: '• OCR improvements. Added notice for incomplete 10x in Tutorial.' },
    { date: '18/01/2024', description: '• Fixed iOS unable to import images.' },
    { date: '17/01/2024', description: '• Added Kaalaa Baunaa and Shamane banners.\n • Updated 1.3 part 1 Event Shop.' },
    { date: '16/01/2024', description: '• Added Centurion banner.' },
    { date: '15/01/2024', description: '• Added "Level Up" function where you can consume your warehouse materials to update arcanist to goal status. Try it out by left clicking an arcanist.' },
    { date: '14/01/2024', description: '• Home UI improvements.' },
    { date: '13/01/2024', description: '• The algorithm for image preprocessing has been modified, requiring observation for evaluation.' },
    { date: '12/01/2024', description: '• Fixed a bug where pity count in summon history is displayed incorrectly when other rarities are present.' },
    { date: '11/01/2024', description: '• Updated ES translations\n • Added Jiu Niangzi, Енисе́й and updated previous missing data.' },
    { date: '10/01/2024', description: '• Updated KR translations\n • vertin wheel vertin wheel vertin wheel.' },
    { date: '08/01/2024', description: '• Improved Golden Thread OCR.\n • Tracker UI changes.' },
    { date: '07/01/2024', description: '• Added French translations thanks to я герой#3673. \n • Improved Japanese translations thanks to yagochi. \n • Fixed X turning into 37 and crop problems. \n • Added 50/50 win/lose indicator.' },
    { date: '06/01/2024', description: '• Added Spanish translations thanks to mgeshagrath. \n • Added Russian translations thanks to spun4ik and dagufz37. \n • Released 1.3 Arcanists.' },
    { date: '05/01/2024', description: '• Big Summon Tracker Update. \n • Added Japanese translations thanks to yagochi.' },
    { date: '04/01/2024', description: '• Added Korean translations thanks to CaptinRegulus.\n • Added Banner Type for Tracker.' },
    { date: '03/01/2024', description: '• Improved i18n. \n • Improved Tracker OCR.' },
    { date: '02/01/2024', description: '• Error log for Summon Tracker.' },
    { date: '29/12/2023', description: '• Added more languages! vi-VN, zh-CN, zh-TW have been fully translated. We need your help!' },
    { date: '28/12/2023', description: '• Summon Tracker out of beta release. \n • Various UI updates.' },
    { date: '26/12/2023', description: '• Improved OCR for 5*. \n • Updated Stage Data and Greedy Method improvements. \n • Added Ezra Theodore and Desert Flanndel.' },
    { date: '25/12/2023', description: '• Improved Activity Settings. UI Improvements.' },
    { date: '24/12/2023', description: '• UI Improvements\n • Wilderness output is now considered for calculations.\n • Merry Christmas.' },
    { date: '23/12/2023', description: '• UI Improvements for goals and crafting list. \n • Added Goal Button.' },
    { date: '21/12/2023', description: '• UI Improvements. \n • Added Goals and Crafting List.' },
    { date: '20/12/2023', description: '• Yet another warehouse update. \n • Summon Tracker. Beta. \n • Added Greedy method to prioritize Purple Materials ' },
    { date: '16/12/2023', description: '• Add names to 1.4 data. UI improvements.\n • Added Activity Settings for Roaring Month and Refills.' },
    { date: '15/12/2023', description: '• Updated storing. Prior selected data will be corrupted, please head to profile to reset.' },
    { date: '14/12/2023', description: '• Warehouse bug fixes (again), changed t6 resonate materials to casket. Sorry for the inconvenience but please reset your warehouse.\n • Added 6, Spathodea and Ulu. Updated arcanists.json\n • Various bug fixes and UI improvements.' },
    { date: '12/12/2023', description: '• Optimized farming route, from the help of Fran!' },
    { date: '05/12/2023', description: '• Added Profile. WIP.' },
    { date: '04/12/2023', description: '• Updated credits, minor bug fixes.' },
    { date: '03/12/2023', description: '• Fixed wrong jsons. Hopefully it is correct now.\n • Soldius. \n • Added 1.2 event shops. Two buttons, all the items.' },
    { date: '02/12/2023', description: '• Fixed warehouse, added Tooth Fairy and Changeling to released.\n • Fixed more warehouse bugs, added reset button.\n • Fixed MORE warehouse bugs.' },
    { date: '01/12/2023', description: '• Warehouse filter is broken, temporary disabled.' },
    { date: '30/11/2023', description: '• Added Warehouse. Fixed wrong Insight levels and unreleased Arcanists' },
    { date: '29/11/2023', description: '• First release.' }
];
